# GitHub Actions Get Started
name: My Workflow

# Controls when the workflow will run
on:
  # Trigger the workflow on push or pull events only on main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allow to run this workflow manually from Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build" 
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

  # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
    # Checks out the repositroy under $GITHUB_WORKSPACE so the job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runner shell
    - name: Runs a one line script
      run: echo Hello World!

    # Runs a set of commands using the runner shell
    - name: Runs a multi-line script
      run: |
        echo Add other actions to build,
        echo test and deploy the project

    
